services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379"
    networks:
      - realstate_network
    restart : always

  realstate:
    container_name: realstate
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/var/www
    networks:
      - realstate_network
    depends_on:
      - redis
    ports:
      - "9000"
    restart : always

networks:
  realstate_network:
    driver: bridge